version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - baking-mysql-volume:/var/lib/mysql

volumes:
  baking-mysql-volume:
    driver: local
